"""empty message

Revision ID: 4bfa43a87045
Revises: 
Create Date: 2021-01-02 15:58:56.845245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfa43a87045'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satisfaction_indicator',
    sa.Column('satisfaction_indicator_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('country', sa.String(length=75), nullable=True),
    sa.Column('indicator_code', sa.String(length=20), nullable=True),
    sa.Column('indicator', sa.String(length=75), nullable=True),
    sa.Column('mesasure_code', sa.String(length=20), nullable=True),
    sa.Column('mesasure', sa.String(length=75), nullable=True),
    sa.Column('inequality_code', sa.String(length=20), nullable=True),
    sa.Column('inequality', sa.String(length=75), nullable=True),
    sa.Column('unit_code', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=75), nullable=True),
    sa.Column('power_code_ref', sa.String(length=20), nullable=True),
    sa.Column('power_code', sa.String(length=75), nullable=True),
    sa.Column('reference_period_code', sa.String(length=20), nullable=True),
    sa.Column('reference_period', sa.String(length=75), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('flag_code', sa.String(length=20), nullable=True),
    sa.Column('flag', sa.String(length=75), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('satisfaction_indicator_id'),
    sa.UniqueConstraint('country_code', 'indicator_code', 'inequality_code')
    )
    op.create_index('country_indicator_code_idx', 'satisfaction_indicator', ['country_code', 'indicator_code', 'inequality_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('country_indicator_code_idx', table_name='satisfaction_indicator')
    op.drop_table('satisfaction_indicator')
    # ### end Alembic commands ###
